### ISSUE TITLE
Story Of Seasons : Friends Of Mineral Town

### ISSUE THREAD

**Issue by taufikjrc** [skyline-emu/skyline-games-list#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1079

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_f3-ampp-10758.php

### Game Behaviour

- Graphics blur.
- Audio available and is fine
- When select name it will crash, because skyline still not add input keyboard feature, so i must playing using save files.
- Missing some texture like grass, plank, stone.
- Game freeze when brush horse, but Audio still playing.
- Game Freeze when go to Hot Spring place with black screen, but Audio still playing.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[logs.zip](https://github.com/skyline-emu/skyline-games-list/files/8643137/logs.zip)

**Comment by K11MCH1** [comment]
```
	Line 129: W4299HOS-3HandleRequest: Cannot find function in service 'hid::IHidServer': 0x5B (91)
	Line 133: W28410HOS-3HandleRequest: Cannot find function in service 'am::ISelfController': 0x3F (63)
	Line 134: W28412HOS-3HandleRequest: Cannot find function in service 'am::ISelfController': 0x3E (62)
	Line 135: W30156HOS-3HandleRequest: Cannot find function in service 'am::ISelfController': 0x3F (63)
	Line 136: W36364HOS-3HandleRequest: Cannot find function in service 'am::ISelfController': 0x3F (63)
```

```
E79799HOS-0Signal: Segmentation fault @ 0x30303030303038 (PC: 0x7CA2928B10) (SVC: SvcWaitSynchronization)
Stack Trace:
* 0x7CA2928B10 (from libskyline.so)
* 0x7CA295A794 (skyline::kernel::svc::WaitSynchronization(skyline::DeviceState const&) from libskyline.so)
* 0x7CA293B068 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from libskyline.so)
* 0x8654170B8 (from sdk.nso.patch)
* 0x86574473C (nn::oe::PopNotificationMessage() from sdk.nso)
* 0x800006C7C (nnMain from main.nso)
* 0x8656B5A2C (nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()) from sdk.nso)
* 0x8000010C0 (from rtld.nso)
E79801HOS-1Signal: Bus error (PC: 0x7CA2928B10) (SVC: SvcWaitSynchronization)
Stack Trace:
* 0x7CA2928B10 (from libskyline.so)
* 0x7CA295A794 (skyline::kernel::svc::WaitSynchronization(skyline::DeviceState const&) from libskyline.so)
* 0x7CA293B068 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from libskyline.so)
* 0x8654170B8 (from sdk.nso.patch)
* 0x86574DC48 (nn::os::detail::MultiWaitImpl::InternalWaitAnyImpl(bool, nn::TimeSpan) from sdk.nso)
* 0x86574DE78 (nn::os::detail::MultiWaitImpl::WaitAnyImpl(bool, nn::TimeSpan) from sdk.nso)
* 0x86574A5F4 (from sdk.nso)
* 0x86574A55C (from sdk.nso)
* 0x86574A54C (from sdk.nso)
* 0x86574C4B8 (from sdk.nso)
* 0x865750984 (from sdk.nso)
* 0x865750930 (from sdk.nso)
```

**Comment by feel2death** [comment]
latest build crashed when load the game and blur still in there but it run 60 fps it could be playable if they fix save and blur issue
phone : poco f3

**Comment by bylaws** [comment]
blur probably depth, maybe fixed in upcoming new gpu

**Comment by deltatux** [comment]
Looks like it works on the Pixel 4a 5G but instead of just blur, it looks like the brightness has been cranked up. It's as if the game is shining a light in my face... It's not playable due to this bug, game seems as stable as previous reports based on my short testing so far though.

Device: Google Pixel 4a 5G
SOC: Snapdragon 765G
Android: 13
Skyline build: 1763

![Screenshot_20230116-212427](https://user-images.githubusercontent.com/59618028/212797207-f6fed50f-596b-4f6b-88fd-b1172d63c9fb.png)

This problem happens no matter which Vulkan driver I've tried so far be it Turnip or Qualcomm proprietary.

**Comment by ikhoeyZX** [comment]
Skyline 2113 fix it but it not fix load from menu (you need new game and then load game from there)

![Screenshot_20230317_112323](https://user-images.githubusercontent.com/79812109/225856382-b6961a15-8df6-4947-8307-ff2f86bae46b.png)
![Screenshot_20230317_164816_Gallery](https://user-images.githubusercontent.com/79812109/225856654-2630753e-f159-4bea-a102-325562445e24.png)

**Comment by ikhoeyZX** [comment]
[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/10999543/emulation.sklog.zip)

**Comment by KrisadaFantasy** [comment]
> [emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/10999543/emulation.sklog.zip) /!\ save game won't load directly if you save at house so save at outside building

Where do you save the game? I try the farm and the city but it still failed to load from menu, fading to white and freeze with music continue playing.

**Comment by ikhoeyZX** [comment]
> > [emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/10999543/emulation.sklog.zip) /!\ save game won't load directly if you save at house so save at outside building
> 
> Where do you save the game? I try the farm and the city but it still failed to load from menu, fading to white and freeze with music continue playing.

What version you use
I'm using base game (v1.0.0) it work
But if you use v1.0.1 it won't work

Here log v1.0.1 (crash when load game)
[Share.txt](https://github.com/skyline-emu/skyline-games-list/files/11381923/Share.txt)

**Comment by ikhoeyZX** [comment]
Base:
https://user-images.githubusercontent.com/79812109/235903539-d50ff705-904a-4fa5-8b01-a0e60553adeb.mp4

V1.0.1

https://user-images.githubusercontent.com/79812109/235903593-be65c694-e9a5-4f5e-869e-86d14d7c89cf.mp4

**Comment by KrisadaFantasy** [comment]
> > > [emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/10999543/emulation.sklog.zip) /!\ save game won't load directly if you save at house so save at outside building
> > 
> > 
> > Where do you save the game? I try the farm and the city but it still failed to load from menu, fading to white and freeze with music continue playing.
> 
> What version you use I'm using base game (v1.0.0) it work But if you use v1.0.1 it won't work
> 
> Here log v1.0.1 (crash when load game) [Share.txt](https://github.com/skyline-emu/skyline-games-list/files/11381923/Share.txt)

I try 1.0.0 on latest mainline skyline but it still not working for me. I try old save, making new save on farm from old save, making new save from farm on new game, but none works.

[emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/11392456/emulation.txt)

I try to see if my log has any difference from you but cannot find anything that stand out.

**Comment by ikhoeyZX** [comment]
Maybe because difference CPU type
Im using exynos 1280

> > > > [emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/10999543/emulation.sklog.zip) /!\ save game won't load directly if you save at house so save at outside building
> > > 
> > > 
> > > Where do you save the game? I try the farm and the city but it still failed to load from menu, fading to white and freeze with music continue playing.
> > 
> > 
> > What version you use I'm using base game (v1.0.0) it work But if you use v1.0.1 it won't work
> > Here log v1.0.1 (crash when load game) [Share.txt](https://github.com/skyline-emu/skyline-games-list/files/11381923/Share.txt)
> 
> I try 1.0.0 on latest mainline skyline but it still not working for me. I try old save, making new save on farm from old save, making new save from farm on new game, but none works.
> 
> [emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/11392456/emulation.txt)
> 
> I try to see if my log has any difference from you but cannot find anything that stand out.

Maybe because we using difference cpu?
Im using exynos 1280

**Comment by KrisadaFantasy** [comment]
> Maybe because difference CPU type Im using exynos 1280 Had you try open save game from new game mode
> 
> Start new game and then load game after intro
> 
> > > > > [emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/10999543/emulation.sklog.zip) /!\ save game won't load directly if you save at house so save at outside building
> > > > 
> > > > 
> > > > Where do you save the game? I try the farm and the city but it still failed to load from menu, fading to white and freeze with music continue playing.
> > > 
> > > 
> > > What version you use I'm using base game (v1.0.0) it work But if you use v1.0.1 it won't work
> > > Here log v1.0.1 (crash when load game) [Share.txt](https://github.com/skyline-emu/skyline-games-list/files/11381923/Share.txt)
> > 
> > 
> > I try 1.0.0 on latest mainline skyline but it still not working for me. I try old save, making new save on farm from old save, making new save from farm on new game, but none works.
> > [emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/11392456/emulation.txt)
> > I try to see if my log has any difference from you but cannot find anything that stand out.

Seems pobbible. My MediaTek Helio G96 is not as good as yours.

I already load the game by going through new game intro and probably have to continue doing so!

**Comment by KrisadaFantasy** [comment]
> Maybe because difference CPU type Im using exynos 1280 Had you try open save game from new game mode
> 
> Start new game and then load game after intro
> 
> > > > > [emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/10999543/emulation.sklog.zip) /!\ save game won't load directly if you save at house so save at outside building
> > > > 
> > > > 
> > > > Where do you save the game? I try the farm and the city but it still failed to load from menu, fading to white and freeze with music continue playing.
> > > 
> > > 
> > > What version you use I'm using base game (v1.0.0) it work But if you use v1.0.1 it won't work
> > > Here log v1.0.1 (crash when load game) [Share.txt](https://github.com/skyline-emu/skyline-games-list/files/11381923/Share.txt)
> > 
> > 
> > I try 1.0.0 on latest mainline skyline but it still not working for me. I try old save, making new save on farm from old save, making new save from farm on new game, but none works.
> > [emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/11392456/emulation.txt)
> > I try to see if my log has any difference from you but cannot find anything that stand out.

With all things I still test last publicly released Edge 69 and I am please to tell you that I manage to continue the game (1.0.5) from menu! I made a fresh install and try to load the game and it works! Then I go to setting and enable material colour, add profile picture and change name, and **it no longer works**.

So it works on fresh install (or after clear all data). I test changing only user name and it stop loading from menu. I don't have willpower to test any further right now on each setting or the last mainline Skyline or the save inside house, but can proclaim here that I can continue the "out-of-building save" from menu in Edge 69 that install without changing any setting.

**Comment by ikhoeyZX** [comment]
![Screenshot_20231217_012421](https://github.com/strato-emu/compat-list/assets/79812109/51fe52f9-8fc9-467a-8634-3f62e001f3b5)
no issue in texture
make sure you save a game OUTSIDE any building, otherwise it will crash emulator
